### PR TITLE
composer 1.3.1

### PR DESCRIPTION
**Pull request by KrzysztofWloch**

### CODE REVIEW

**Comment by bastiankoetsier** [comment]
+1
I thought more of something like literally pinning composer version, but that works anyway 😅

**Comment by bastiankoetsier** [comment]
+1
even better :)

**Comment by vgorely** [comment]
@KrzysztofWloch @bastiankoetsier 
Guys, could you please explain why it was needed to hardcode the 1.3.1 version of composer?

**Comment by KrzysztofWloch** [comment]
@vgorely It's better to rely on specific version of dependency when building docker images, also this version fixes xdebug interference.

**Pull request merged**
